server:
  port: 8081

spring:
  datasource:
    url: jdbc:postgresql://localhost:5433/resource_db
    username: user
    password: password
  jpa:
    hibernate:
      ddl-auto: update

song:
  feign:
    path: http://localhost:8082