server:
  port: 8081

spring:
  datasource:
    url: jdbc:postgresql://localhost/resource_db
    username: postgres
    password: postgres
  jpa:
    hibernate:
      ddl-auto: update

song:
  feign:
    path: http://localhost:8082