server:
  port: 8081

spring:
  application:
    name: resource-service
  datasource:
    url: ${SPRING_DATASOURCE_URL:jdbc:postgresql://localhost:5433/resource_db}
    username: ${SPRING_DATASOURCE_USERNAME:user}
    password: ${SPRING_DATASOURCE_PASSWORD:password}

file-storage:
  aws:
    region: us-east-1
    credentials:
      access-key: test
      secret-key: test
    s3:
      endpoint: http://localhost:4566
      bucket-name: your-music-bucket

song:
  service-name: ${SONG_SERVICE_NAME:song-service}

eureka:
  instance:
    instance-id: ${spring.application.name}:${random.uuid}
  client:
    registry-fetch-interval-seconds: 5
    service-url:
      defaultZone: ${EUREKA_SERVER:http://localhost:8080/eureka}